// <auto-generated />
namespace Apartmani.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Inquery : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Inquery));
        
        string IMigrationMetadata.Id
        {
            get { return "201807311308573_Inquery"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
